version: '3.4'

services:
  desafio.amcom:
    image: ${DOCKER_REGISTRY-}desafioamcom
    build:
      context: .
      dockerfile: src/Desafio.AMcom/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5000:80      
      - 5001:443      
    networks:
      - amcom-network
networks:
    amcom-network:
        driver: bridge