version: '3.4'

services:
  desafio.amcom:
    image: desafioamcom
    build:
      context: ./src
      dockerfile: ./Desafio.AMcom/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 8080:80      
    networks:
      - amcom-network
networks:
    amcom-network:
        driver: bridge